#!/bin/bash

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

clear
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}--            Installation of Cqlsh                      ---${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e " "
mkdir /workspace/workshop-spring-reactive/tools 2>/dev/null
echo -e "${GREEN}[OK]${NC} - Tools folder has been created
cd /workspace/workshop-spring-reactive/tools
wget https://downloads.datastax.com/enterprise/cqlsh-astra.tar.gz \
        && tar xvzf cqlsh-astra.tar.gz \
        && rm -f cqlsh-astra.tar.gz 1>/dev/null
echo -e "${GREEN}[OK]${NC} - Package has been downloaded
cd /workspace/workshop-spring-reactive
chmod 700 /workspace/workshop-spring-reactive/cqlsh 
echo -e "${GREEN}[OK]${NC} - Permissions Set

cd /workspace/workshop-spring-reactive
npm exec -y astra-setup workshops spring_petclinic
set -a
source /workspace/workshop-spring-reactive/.env
set +a
mvn test -Dtest=com.datastax.workshop.petclinic.Test01_Connectivity > /dev/null
echo -e "${GREEN}[OK]${NC} - Secure Connect Bundle downloaded
echo -e "${GREEN}[OK]${NC} - Launching CQLSH....
./cqlsh



